apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: eureka
  name: eureka
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: eureka
  type: ClusterIP
status:
  loadBalancer: {}
