apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
  name: mario
  namespace: default
spec:
  virtualhost:
    fqdn: mario.taskoo.net
  routes:
    - services:
      - name: mario
        port: 80
---
