apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
  name: mario
  namespace: default
spec:
  virtualhost:
    fqdn: mario.taskoo.net
  routes:
    - services:
      - name: mario
        port: 80
---
apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
  name: springboot
  namespace: default
spec:
  virtualhost:
    fqdn: springboot.taskoo.net
  routes:
    - services:
      - name: springboot
        port: 8080
---
apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
  name: argocd-proxy
  namespace: argocd
spec:
  virtualhost:
    fqdn: argocd.taskoo.net
    tls:
      passthrough: true
  tcpproxy:
    services:
    - name: argocd-server
      port: 80

