apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
  name: mario
  namespace: default
spec:
  virtualhost:
    fqdn: mario.taskoo.net
  routes:
    - services:
      - name: mario
        port: 80
---
apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
  name: springboot
  namespace: default
spec:
  virtualhost:
    fqdn: springboottest.taskoo.net
  routes:
    - services:
      - name: springboot
        port: 8080
---
apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
  name: eureka
  namespace: default
spec:
  virtualhost:
    fqdn: eureka.taskoo.net
  routes:
    - services:
      - name: eureka
        port: 8080

