apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
  name: mario
  namespace: default
spec:
  virtualhost:
    fqdn: mario.taskoo.net
  routes:
    - services:
      - name: mario
        port: 80
---
apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
  name: springboot
  namespace: default
spec:
  virtualhost:
    fqdn: springboot.taskoo.net
  routes:
    - services:
      - name: springboot
        port: 8080
---

