
apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
  name: name-example-foo
  namespace: canary
spec:
  virtualhost:
    fqdn: test111.aikoo.net
  routes:
    - services:
      - name: canary-service
        port: 80
---
apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
  name: name-example-foo
  namespace: bluegreen
spec:
  virtualhost:
    fqdn: test222.aikoo.net
  routes:
    - services:
      - name: rollout-bluegreen-active
        port: 80
---
apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
  name: argocd-proxy
  namespace: argocd
spec:
  virtualhost:
    fqdn: argocd.aikoo.net
    tls:
      passthrough: true
  tcpproxy:
    services:
    - name: argocd-server
      port: 80
