
apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
  name: name-example-foo
  namespace: default
spec:
  virtualhost:
    fqdn: test3.aikoo.net
  routes:
    - services:
      - name: kuard
        port: 80
