
apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
  name: name-example-foo
  namespace: tanzu-system-monitoring
spec:
  virtualhost:
    fqdn: test3.aikoo.net
  routes:
    - services:
      - name: prometheus-server
        port: 80
